browser=chrome
url=https://www.carrefoursa.com/
customerEmail=azimkaya777@gmail.com
password=A.Kaya77143321
yeni:
yeni pasword:
customerEmail=azimkaya33777@gmail.com
password=A.Kaya771433213
customerEmail=azimkaya41777@gmail.com
password=A.Kaya7714332145
customerEmail=azimkaya4123777@gmail.com
password=A.Kaya77143321457